server:
  port: 7001
  tomcat:
    threads:
      max: 50
    accept-count: 50
    max-connections: 100
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
  sentinel:
    enabled: true
hm:
  swagger:
    title: "购物车服务接口文档"
    package: com.hmall.cart.controller
  db:
    database: hm-cart
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true