server:
  port: 7000
hm:
  swagger:
    title: "黑马商场商品服务接口文档"
    package: com.hmall.item.controller
  db:
    database: hm-item
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123